### ISSUE TITLE
unable to delete orphaned pool

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-openstack-lbaasv2-driver#254] opened 2016-09-27 10:47 UTC
#### Agent Version

f5-openstack-agent-9.0.3-1.noarch
f5-icontrol-rest-1.0.9-1.noarch
f5-openstack-lbaasv2-driver-8.0.8-1.noarch
f5-sdk-1.2.0-1.noarch
#### Operating System

centos7
#### OpenStack Release

Mitaka (Packstack)
#### Description

After deleting the listener I was unable to delete an existing (orphaned) pool.  Workaround was to delete directly from database (not sure how safe/unsafe that is).

```
[user@centos ~(keystone_user)]$ neutron lbaas-pool-delete 98cf300a-c44b-4f06-8550-a10f6442c1a4
An error happened in the driver
Neutron server returns request_ids: ['req-5e32b9ce-5afd-41bb-8e84-d6b35da8d098']

[user@centos ~(keystone_user)]$ neutron lbaas-pool-show 98cf300a-c44b-4f06-8550-a10f6442c1a4
+---------------------+------------------------------------------------+
| Field               | Value                                          |
+---------------------+------------------------------------------------+
| admin_state_up      | True                                           |
| description         |                                                |
| healthmonitor_id    |                                                |
| id                  | 98cf300a-c44b-4f06-8550-a10f6442c1a4           |
| lb_algorithm        | ROUND_ROBIN                                    |
| listeners           |                                                |
| loadbalancers       | {"id": "58ba90fa-f0b5-49b4-9a4f-79918c35be11"} |
| members             |                                                |
| name                | pool1                                          |
| protocol            | HTTP                                           |
| session_persistence |                                                |
| tenant_id           | 6e9c238c72ce45d891a4b2552281a159               |
```

From /var/log/neutron/server.log

```
2016-09-27 06:09:23.782 969 INFO neutron_lbaas.services.loadbalancer.plugin [req-c587c256-a66e-4825-a2e2-c82be5f16590 7022acb128b64d5bb1eab7adc09cef2a 6e9c238c72ce45d891a4b2552281a159 - - -] Calling driver operation PoolManager.delete
2016-09-27 06:09:23.782 969 ERROR f5lbaasdriver.v2.bigip.driver_v2 [req-c587c256-a66e-4825-a2e2-c82be5f16590 7022acb128b64d5bb1eab7adc09cef2a 6e9c238c72ce45d891a4b2552281a159 - - -] Exception: pool delete: 'NoneType' object has no attrib
ute 'loadbalancer'
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin [req-c587c256-a66e-4825-a2e2-c82be5f16590 7022acb128b64d5bb1eab7adc09cef2a 6e9c238c72ce45d891a4b2552281a159 - - -] There was an error in the driver
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin Traceback (most recent call last):
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 486, in _call_driver_operation
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin     driver_method(context, db_entity)
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/neutron_lbaas/drivers/f5/driver_v2.py", line 114, in delete
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin     self.driver.f5.pool.delete(context, pool)
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/oslo_log/helpers.py", line 46, in wrapper
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin     return method(*args, **kwargs)
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/lib/python2.7/site-packages/f5lbaasdriver/v2/bigip/driver_v2.py", line 415, in delete
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin     raise e
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin AttributeError: 'NoneType' object has no attribute 'loadbalancer'
2016-09-27 06:09:23.783 969 ERROR neutron_lbaas.services.loadbalancer.plugin
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource [req-c587c256-a66e-4825-a2e2-c82be5f16590 7022acb128b64d5bb1eab7adc09cef2a 6e9c238c72ce45d891a4b2552281a159 - - -] delete failed
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource Traceback (most recent call last):
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 84, in resource
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 532, in delete
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     return self._delete(request, id, **kwargs)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 148, in wrapper
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     self.force_reraise()
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 138, in wrapper
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 554, in _delete
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     obj_deleter(request.context, id, **kwargs)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 902, in delete_pool
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     self._call_driver_operation(context, driver.pool.delete, db_pool)
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 494, in _call_driver_operation
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource     raise loadbalancerv2.DriverError()
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource DriverError: An error happened in the driver
2016-09-27 06:09:23.802 969 ERROR neutron.api.v2.resource
```

"workaround"

```
MariaDB [neutron]> select * from lbaas_pools;
+----------------------------------+--------------------------------------+-------+-------------+----------+--------------+------------------+----------------+---------------------+------------------+--------------------------------------+
| tenant_id                        | id                                   | name  | description | protocol | lb_algorithm | healthmonitor_id | admin_state_up | provisioning_status | operating_status | loadbalancer_id                      |
+----------------------------------+--------------------------------------+-------+-------------+----------+--------------+------------------+----------------+---------------------+------------------+--------------------------------------+
| 6e9c238c72ce45d891a4b2552281a159 | 98cf300a-c44b-4f06-8550-a10f6442c1a4 | pool1 |             | HTTP     | ROUND_ROBIN  | NULL             |              1 | PENDING_DELETE      | ONLINE           | 58ba90fa-f0b5-49b4-9a4f-79918c35be11 |
+----------------------------------+--------------------------------------+-------+-------------+----------+--------------+------------------+----------------+---------------------+------------------+--------------------------------------+
1 row in set (0.00 sec)

MariaDB [neutron]> delete from lbaas_pools where id='98cf300a-c44b-4f06-8550-a10f6442c1a4';
Query OK, 1 row affected (0.02 sec)
```

Steps to reproduce

```
neutron lbaas-loadbalancer-create --name lb1 private_subnet
neutron lbaas-listener-create --name listener1 --loadbalancer lb1 --protocol HTTP --protocol-port 80
neutron lbaas-pool-create --name pool1 --lb-algorithm ROUND_ROBIN --listener listener1 --protocol HTTP
neutron lbaas-listener-delete listener1
neutron lbaas-pool-delete pool1
```
#### Deployment

Using undercloud VXLAN with external BIG-IP on a allinone OpenStack deployment.
#### OpenStack Release

Mitaka

**Comment by richbrowne** [comment] 2016-09-30 14:51
Thanks for this write up.  We are doing work now to support detached pools.  In liberty, the Neutron API disallowed the deletion of a listener if it had an attached pool.  Moving forward to Mitaka this restriction was removed to support detached pools.  In the near term we can check the listener's default_pool_id, and disallow removal.  The real solution is to support detached pools, which is in progress.

**Comment by dflanigan** [comment] 2016-10-28 17:23
this is duplicate of agent issue 315

**Comment by mattgreene** [comment] 2016-12-21 22:18
Issue resolved by merge https://github.com/F5Networks/f5-openstack-agent/pull/448

**Closed by mattgreene** 2016-12-21 22:18 UTC
Labels: bug, duplicate, P2, S3
