### ISSUE TITLE
Limit length of tunnel name.

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#245] opened 2016-09-13 18:13 UTC
I have been playing around with the disconnected network feature and I am seeing a failure when a loadbalancer is created b/c the envionment_name + the tenant id + “disconnected_network” exceed 64 chars in length.  So we need to accommodate this be setting a maximum on the length of the environment_name.  However, we could probably make that limit a little longer if we abbreviated “disconnected_network”.  We can discuss this tomorrow, but we need to add a way to let the user know that the env name is too long when he uses the tool in any event.

Proposed incremental solution:
1. Document length limitation, 2. Spit out a log message when a string exceeds max length, 3. Auto-truncate to fit within max length.

**Comment by mattgreene** [comment] 2016-10-14 17:16
Duplicate of https://github.com/F5Networks/f5-openstack-agent/issues/281

**Comment by dflanigan** [comment] 2016-11-21 21:06
agent issue 281 is done.

**Closed by dflanigan** 2016-11-21 21:06 UTC
Labels: bug, duplicate, P2, S3
